export const Colors = {
    brandPrimary: '#0D575C',
    brandGradientStart: '#6E7C7D',
    brandGradientEnd: '#192D3A',
    brandDark:'#054347',
    brandLight:'#99BCBE',
    componentBackground: '#FCFDFA',
    componentBackgroundActive: 'rgba(53, 71, 80, 0.05)',
    componentBackgroundFloat: '#FCFDFA',
    dim: 'rgba(0, 0, 0, 0.25)',
    systemRed: '#9E2D2F',
    CreatorPrimary:'#BB4E2D',
    CreatorLight:'#F09F86',
    CreatorDark:'#993516',
    CreatorGradient: 'linear-gradient(135deg, #BB4E2D 0%, #993516 100%)',

  // Greyscale
    grey01: '#E6ECEF',
    grey02: '#D3D8DF',
    grey03: '#BAC1C5',
    grey04: '#A0A8AD',
    grey05: '#788388',
    grey06: '#444F55',
    grey07: '#252C30',

    creatorgrey01:'#F2EEED',
    creatorgrey02:'#E4DCDA',
    creatorgrey03:'#CEC8C6',
    creatorgrey04:'#B3A7A4',
    creatorgrey05:'#887E7A',
    creatorgrey06:'#524844',
    creatorgrey07:'#2F2725',

  // Players
    player1P: '#8A6262',
    player2P: '#6E7463',
    player3P: '#766178',
};

export const FontStyles = {
    headlineLarge: {
    fontFamily: 'Pretendard, sans-serif',
    fontWeight: 600,
    fontSize: 36,
    lineHeight: '44px',
    letterSpacing: '-2.5%',
    },
    headlineNormal: {
    fontFamily: 'Pretendard, sans-serif',
    fontWeight: 600,
    fontSize: 28,
    lineHeight: '36px',
    letterSpacing: '-2.5%',
    },
    headlineSmall: {
    fontFamily: 'Pretendard, sans-serif',
    fontWeight: 600,
    fontSize: 24,
    lineHeight: '32px',
    letterSpacing: '-2.5%',
    },
    title: {
    fontFamily: 'Pretendard, sans-serif',
    fontWeight: 600,
    fontSize: 18,
    lineHeight: '24px',
    letterSpacing: '-2.5%',
    },
    button: {
    fontFamily: 'Pretendard, sans-serif',
    fontWeight: 600,
    fontSize: 17,
    lineHeight: '24px',
    letterSpacing: '-2.5%',
    },
    bodyBold: {
    fontFamily: 'Pretendard, sans-serif',
    fontWeight: 600,
    fontSize: 16,
    lineHeight: '24px',
    letterSpacing: '-2.5%',
    },
    body: {
    fontFamily: 'Pretendard, sans-serif',
    fontWeight: 400,
    fontSize: 16,
    lineHeight: '24px',
    letterSpacing: '-2.5%',
    },
    caption: {
    fontFamily: 'Pretendard, sans-serif',
    fontWeight: 400,
    fontSize: 14,
    lineHeight: '16px',
    letterSpacing: '-2.5%',
    },
  logo: {
    fontFamily: 'Cafe24 Ohsquare air',
    fontWeight: 500, 
    fontSize: 26,
    lineHeight: '44px',
    letterSpacing: '0',
},
};
