# 본 워크플로우는 GitHub Actions를 사용하여 코드 푸시 및 풀 리퀘스트 시 자동으로 빌드 체크를 수행함
#빌드 과정에서 발생하는 에러는 로그에 기록되어 깃헙 레포지토리-Actions 탭-워크플로우의 푸시 내역에서 확인 가능
name: Build Check

on:
  push:
    branches: [ "main", "feature/*" ] # 푸시할 때마다 실행
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # 프로젝트 Node 버전과 맞춤

      - name: Install dependencies
        run: npm install

      - name: Run build check
        run: npm run build # 여기서 에러가 나면 로그가 기록됩니다.